global:
  evaluation_interval: 5s

rule_files:
  - /etc/vmalert/rules/*.yaml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      scheme: http
      path_prefix: /
      timeout: 10s