services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - data-zookeeper-log-1:/var/lib/zookeeper/log
      - data-zookeeper-data-1:/var/lib/zookeeper/data
    networks:
      - confluent
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888

  kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    restart: always
    container_name: kafka-1
    hostname: kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "19092:19092"
    networks:
      - confluent
    volumes:
      - data-kafka-1:/var/lib/kafka/data
      - "${PATH_TO_NFS}/certs/kafka-1-creds:/etc/kafka/secrets:ro"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_DELETE_TOPIC_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LISTENERS: SSL://0.0.0.0:9093,PLAINTEXT://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka-1:9093,PLAINTEXT://kafka-1:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka-1.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-1_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka-1_sslkey_creds
      KAFKA_SSL_KEY_PASSWORD: "${SSL_PASSWORD}"
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka-1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-1_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:CN=kafka-1;User:CN=kafka-2;User:CN=kafka-3;User:ANONYMOUS
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_PRINCIPAL_MAPPING_RULES: DEFAULT

  kafka-2:
    image: confluentinc/cp-kafka:7.4.4
    restart: always
    container_name: kafka-2
    hostname: kafka-2
    depends_on:
      - zookeeper
      - kafka-1
    ports:
      - "9095:9095"
      - "19093:19093"
    networks:
      - confluent
    volumes:
      - data-kafka-2:/var/lib/kafka/data
      - "${PATH_TO_NFS}/certs/kafka-2-creds:/etc/kafka/secrets:ro"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_DELETE_TOPIC_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LISTENERS: SSL://0.0.0.0:9095,PLAINTEXT://0.0.0.0:19093
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka-2:9095,PLAINTEXT://kafka-2:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka-2.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-2_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka-2_sslkey_creds
      KAFKA_SSL_KEY_PASSWORD: "${SSL_PASSWORD}"
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka-2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-2_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:CN=kafka-1;User:CN=kafka-2;User:CN=kafka-3;User:ANONYMOUS
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_PRINCIPAL_MAPPING_RULES: DEFAULT

  kafka-3:
    image: confluentinc/cp-kafka:7.4.4
    restart: always
    container_name: kafka-3
    hostname: kafka-3
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-2
    ports:
      - "9097:9097"
      - "19095:19095"
    networks:
      - confluent
    volumes:
      - data-kafka-3:/var/lib/kafka/data
      - "${PATH_TO_NFS}/certs/kafka-3-creds:/etc/kafka/secrets:ro"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_DELETE_TOPIC_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LISTENERS: SSL://0.0.0.0:9097,PLAINTEXT://0.0.0.0:19095
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka-3:9097,PLAINTEXT://kafka-3:19095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka-3.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-3_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka-3_sslkey_creds
      KAFKA_SSL_KEY_PASSWORD: "${SSL_PASSWORD}"
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka-3.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-3_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:CN=kafka-1;User:CN=kafka-2;User:CN=kafka-3;User:ANONYMOUS
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_PRINCIPAL_MAPPING_RULES: DEFAULT

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8888:8080"
    networks:
      - confluent
    environment:
      KAFKA_CLUSTERS_0_NAME: first-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "${FIRST_CLUSTER_BOOTSTRAPSERVERS}"
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /ssl/kafka.kafka-1.keystore.pkcs12
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: "${SSL_PASSWORD}"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /ssl/kafka.kafka-1.truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: "${SSL_PASSWORD}"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_CLIENT_AUTH: required
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_1_BOOTSTRAP_SERVERS: "${SECOND_CLUSTER_BOOTSTRAPSERVERS}"
      KAFKA_CLUSTERS_1_NAME: second-kafka-cluster
    volumes:
      - "${PATH_TO_NFS}/certs/kafka-1-creds:/ssl:ro"

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.4
    container_name: schema-registry
    restart: always
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8081:8081"
    networks:
      - confluent
    volumes:
      - "${PATH_TO_NFS}/certs/kafka-1-creds:/etc/schema-registry/secrets:ro"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_DEBUG: "true"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SSL://kafka-1:9093,SSL://kafka-2:9095,SSL://kafka-3:9097
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SSL
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: /etc/schema-registry/secrets/kafka.kafka-1.keystore.pkcs12
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: "${SSL_PASSWORD}"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_TYPE: PKCS12
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /etc/schema-registry/secrets/kafka.kafka-1.truststore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: "${SSL_PASSWORD}"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: "${SSL_PASSWORD}"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      SCHEMA_REGISTRY_KAFKASTORE_SSL_CLIENT_AUTH: required
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_MIN_INSYNC_REPLICAS: 2
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_LOG4J_LOGGERS: "kafka=INFO,org.apache.zookeeper=INFO,io.confluent=INFO"

  kafka-second-1:
    image: bitnamilegacy/kafka:3.7
    restart: always
    networks:
      - confluent
    container_name: kafka-second-1
    hostname: kafka-second-1
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 10 
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-second-1:9092,EXTERNAL://kafka-second-1:9094
      KAFKA_ENABLE_KRAFT: yes
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: second-kafka-cluster
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 10@kafka-second-1:9093,20@kafka-second-2:9093,30@kafka-second-3:9093
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
    volumes:
      - data-kafka-second-1:/bitnami/kafka

  kafka-second-2:
    image: bitnamilegacy/kafka:3.7
    restart: always
    networks:
      - confluent
    container_name: kafka-second-2
    hostname: kafka-second-2
    ports:
      - "9096:9094"
    environment:
      KAFKA_CFG_NODE_ID: 20 
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-second-2:9092,EXTERNAL://kafka-second-2:9094
      KAFKA_ENABLE_KRAFT: yes
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: second-kafka-cluster
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 10@kafka-second-1:9093,20@kafka-second-2:9093,30@kafka-second-3:9093
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
    volumes:
      - data-kafka-second-2:/bitnami/kafka

  kafka-second-3:
    image: bitnamilegacy/kafka:3.7
    restart: always
    networks:
      - confluent
    container_name: kafka-second-3
    hostname: kafka-second-3
    ports:
      - "9098:9094"
    environment:
      KAFKA_CFG_NODE_ID: 30
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-second-3:9092,EXTERNAL://kafka-second-3:9094
      KAFKA_ENABLE_KRAFT: yes
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: second-kafka-cluster
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 10@kafka-second-1:9093,20@kafka-second-2:9093,30@kafka-second-3:9093
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
    volumes:
      - data-kafka-second-3:/bitnami/kafka

  mirrormaker:
    image: confluentinc/cp-kafka:7.3.0
    hostname: mirrormaker
    container_name: mirrormaker
    environment:
      KAFKA_MM_SESSION_TIMEOUT_MS: "30000"
      KAFKA_MM_HEARTBEAT_INTERVAL_MS: "10000"
      KAFKA_MM_REQUEST_TIMEOUT_MS: "60000"
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/connect-log4j.properties"
      KAFKA_OPTS: "-XX:-UseContainerSupport -XX:+UnlockExperimentalVMOptions -XX:+DisableAttachMechanism -XX:+UseG1GC"
      JAVA_TOOL_OPTIONS: "-XX:-UseContainerSupport"
    command:
      - bash
      - -c
      - |
        echo "Starting MirrorMaker 2..."
        echo "KAFKA_OPTS: ${KAFKA_OPTS}"
        echo "JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}"
        /usr/bin/connect-mirror-maker /etc/mm2.properties
    volumes:
      - ./files/mm2.properties:/etc/mm2.properties:ro
      - "${PATH_TO_NFS}/certs/kafka-1-creds:/etc/kafka/secrets:ro"
    networks:
      - confluent

  kafka-connect:
    build:
      context: ./infra/kafka-connect
      dockerfile: Dockerfile
    hostname: kafka-connect
    container_name: kafka-connect      
    ports:
      - "8083:8083"  # REST API Kafka Connect
      - "9875:9875"
      - "9876:9876"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "${FIRST_CLUSTER_BOOTSTRAPSERVERS}"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: 'kafka-connect'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'localhost'
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-config-storage'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offset-storage'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status-storage'
      # CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      # CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      # CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      # Конвертеры
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
      CONNECT_SECURITY_PROTOCOL: "SSL"
      CONNECT_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/kafka.kafka-1.truststore.jks"
      CONNECT_SSL_TRUSTSTORE_PASSWORD: "${SSL_PASSWORD}"
      CONNECT_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/kafka.kafka-1.keystore.pkcs12"
      CONNECT_SSL_KEYSTORE_PASSWORD: "${SSL_PASSWORD}"
      CONNECT_SSL_KEY_PASSWORD: "${SSL_PASSWORD}"
      CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      CONNECT_PRODUCER_SECURITY_PROTOCOL: "SSL"
      CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/kafka.kafka-1.truststore.jks"
      CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD: "${SSL_PASSWORD}"
      CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/kafka.kafka-1.keystore.pkcs12"
      CONNECT_PRODUCER_SSL_KEYSTORE_PASSWORD: "${SSL_PASSWORD}"
      
      CONNECT_CONSUMER_SECURITY_PROTOCOL: "SSL"
      CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/kafka.kafka-1.truststore.jks"
      CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD: "${SSL_PASSWORD}"
      CONNECT_CONSUMER_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/kafka.kafka-1.keystore.pkcs12"
      CONNECT_CONSUMER_SSL_KEYSTORE_PASSWORD: "${SSL_PASSWORD}"
    volumes:
      - "${PATH_TO_NFS}/infra/kafka-connect/confluent-hub-components:/etc/kafka-connect/jars:ro"
      - "${PATH_TO_NFS}/certs/kafka-1-creds:/etc/kafka/secrets:ro"
      - "${PATH_TO_NFS}/products:/data:rw"
    networks:
      - confluent

  data-publisher:
    build:
      context: ./scripts/data-publisher
      dockerfile: Dockerfile
    container_name: data-publisher
    volumes:
      - "${PATH_TO_NFS}/products:/app/data:rw"
      - "${PATH_TO_NFS}/certs/kafka-client:/app/certs:ro"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "${FIRST_CLUSTER_BOOTSTRAPSERVERS}"
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
    networks:
      - confluent

  control-ban-words:
    build:
      context: ./scripts/control-ban-words
      dockerfile: Dockerfile  
    container_name: control-ban-words
    ports:
      - "6068:6068"
    environment:
      KAFKA_BROKERS: "${FIRST_CLUSTER_BOOTSTRAPSERVERS}"
      MESSAGES_TOPIC: ban-words
    volumes:
      - ./scripts/control-ban-words/app/.:/app
      - "${PATH_TO_NFS}/certs/kafka-client:/app/certs:ro"
    networks:
      - confluent

  client-api:
    build:
      context: ./scripts/client-api
      dockerfile: Dockerfile
    container_name: client-api
    ports:
      - "6078:6078"
    environment:
      KAFKA_BROKERS: "${FIRST_CLUSTER_BOOTSTRAPSERVERS}"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CLIENT_SEARCHES_TOPIC: client-searches
      RECOMMENDATION_BROKERS: "${SECOND_CLUSTER_BOOTSTRAPSERVERS}"
      RECOMMENDATIONS_TOPIC: client-recommendations
    volumes:
      - ./scripts/client-api/app/.:/app
      - "${PATH_TO_NFS}/certs/kafka-client:/app/certs:ro"
    networks:
      - confluent

volumes:
  data-zookeeper-log-1:
  data-zookeeper-data-1:
  data-kafka-1:
  data-kafka-2:
  data-kafka-3:
  data-kafka-second-1:
  data-kafka-second-2:
  data-kafka-second-3:  

networks:
  confluent:
    driver: bridge