version: '3.8'


services:
 kafka-1:
   image: bitnamilegacy/kafka:3.7
   container_name: kafka-1
   hostname: kafka-1
   ports:
     - "9092:9092"
     - "9093:9093"
   environment:
     KAFKA_ENABLE_KRAFT: "yes"
     KAFKA_CFG_NODE_ID: 1
     KAFKA_CFG_PROCESS_ROLES: "broker,controller"
     KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9095"
     KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"


     KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9093,CONTROLLER://:9095
     KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:9093
     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
     KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT


     KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
     KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
     KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


     KAFKA_KRAFT_CLUSTER_ID: kraft-cluster
   volumes:
     - kafka_data:/bitnami/kafka
   networks:
     - confluent


 nifi:
   image: apache/nifi:1.21.0
   container_name: nifi
   user: "root"
   ports:
     - "8080:8080"
   environment:
     NIFI_WEB_HTTP_PORT: 8080
   volumes:
     - ./nifi_data:/opt/nifi/nifi-current/data
   networks:
     - confluent

volumes:
 kafka_data:
 nifi_data:

networks:
 confluent: